camunda.bpm:
  default-serialization-format: application/json
  metrics.enabled: false
  client:
    base-url: http://localhost:7777/engine-rest
    async-response-timeout: 10000
    worker-id: carbonReductorWorker-1

carbon-reductor:
  carbon-aware-api:
    # Enable or disable the Carbon Aware Sdk usage (default is true)
    # enabled: true
  carbon-aware-computing:
    # Enable or disable the Carbon Aware Computing API usage (default is false)
    # enabled: true
    # basePath: "https://forecast.carbon-aware-computing.com"
    # apiKey: <api-key>
