version: "3.9"
services:

  carbon-aware-webapi:
    image: enviteconsulting/carbon-aware-sdk-webapi:0.0.2
    container_name: carbon-aware-webapi
    environment:
      - DataSources__EmissionsDataSource=WattTime
      - DataSources__ForecastDataSource=WattTime
      - DataSources__Configurations__WattTime__Type=WattTime
      - DataSources__Configurations__WattTime__Username=<myWattTimeUsername>
      - DataSources__Configurations__WattTime__Password=<myWattTimePassword>
    healthcheck:
      test: curl --fail 'http://localhost:80/emissions/forecasts/current?location=westus' || exit 1
      interval: 5s
      retries: 5
      start_period: 3s
      timeout: 2s
    ports:
      - "8090:80"

  camunda-7-carbon-reductor-connector:
    image: enviteconsulting/camunda-7-carbon-reductor-connector:0.0.1
    build:
      context: ../
      dockerfile: camunda-carbon-reductor-c7/Dockerfile
    container_name: camunda-7-carbon-reductor-connector
    depends_on:
      carbon-aware-webapi:
        condition: service_healthy
      carbon-reductor-c7-example-workflow:
        condition: service_healthy
    environment:
      - BASE_URL=http://carbon-reductor-c7-example-workflow:7777/engine-rest
      - ASYNC_RESPONSE_TIMEOUT=10000
      - WORKER_ID=carbonReductorWorker-1
      # To enable or disable the Carbon Aware SDK usage
      - CARBON-REDUCTOR_CARBON-AWARE-API_ENABLED=true
      # To override the URL of the carbon api you could use the following variable
      - CARBON-REDUCTOR_CARBON-AWARE-API_BASE-PATH=http://carbon-aware-webapi:80
      # To enable or disable the Carbon Aware Computing API usage
      # - CARBON-REDUCTOR-CARBON_AWARE_COMPUTING_ENABLED=true
      # - CARBON-REDUCTOR-CARBON_AWARE_COMPUTING_API_KEY=<api-key>
    ports:
      - "8080:8080"

  carbon-reductor-c7-example-workflow:
    image: enviteconsulting/carbon-reductor-c7-example-workflow:0.0.2
    container_name: carbon-reductor-c7-example-workflow
    healthcheck:
      test: curl --fail 'http://localhost:7777/engine-rest/engine' || exit 1
      interval: 5s
      retries: 5
      start_period: 3s
      timeout: 2s
    ports:
      - "7777:7777"
