zeebe:
  client:
    cloud:
      clientId: ${CLIENT_ID}
      clusterId: ${CLUSTER_ID}
      clientSecret: ${CLIENT_SECRET}
      region: ${CLIENT_REGION}

carbon-reductor:
  carbon-aware-api:
  # Enable or disable the Carbon Aware Sdk usage (default is true)
  # enabled: true
  carbon-aware-computing:
  # Enable or disable the Carbon Aware Computing API usage (default is false)
  # enabled: true
  # basePath: "https://forecast.carbon-aware-computing.com"
  # apiKey: <api-key>