camunda:
  client:
    auth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
    cluster-id: ${CLIENT_ID}
    region: ${CLIENT_REGION}
    mode: ${CLIENT_MODE}

carbon-reductor:
  carbon-aware-api:
  # Enable or disable the Carbon Aware Sdk usage (default is true)
  # enabled: true
  carbon-aware-computing:
  # Enable or disable the Carbon Aware Computing API usage (default is false)
  # enabled: true
  # basePath: "https://forecast.carbon-aware-computing.com"
  # apiKey: <api-key>
