name: Build & Upload

on:
  workflow_dispatch:
    inputs:
      C8:
        description: 'C8'
        required: false
        type: boolean
      C7:
        description: 'C7'
        required: false
        type: boolean
      TAG:
        description: 'the tag to be built'
        required: true
        type: string

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v${{ inputs.TAG }}'
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          if [ "$C8" = true ]
          then
            echo "Building C8" && \
            docker buildx build --push --platform linux/arm64/v8,linux/amd64 \
              -t enviteconsulting/camunda-8-carbon-reductor-connector:latest \
              -t enviteconsulting/camunda-8-carbon-reductor-connector:${{ inputs.TAG }} \
              -f camunda-carbon-reductor-c8/Dockerfile \
              .
          else
            echo "Nothing to build for C8"
          fi
          if [ "$C7" = true ]
          then
            echo "Building C7" && \
            docker buildx build --push --platform linux/arm64/v8,linux/amd64 \
              -t enviteconsulting/camunda-7-carbon-reductor-connector:latest \
              -t enviteconsulting/camunda-7-carbon-reductor-connector:${{ inputs.TAG }} \
              -f camunda-carbon-reductor-c7/Dockerfile \
              .
          else
            echo "Nothing to build for C7"
          fi
        env:
          C8: ${{ inputs.c8 }}
          C7: ${{ inputs.c7 }}
