name: Build & Upload

on:
  workflow_dispatch:
    inputs:
      C8:
        description: 'C8'
        required: false
        type: boolean
      C7:
        description: 'C7'
        required: false
        type: boolean

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          if [ "$C8" = true ]
          then
            echo "Building C8" && \
            docker-compose -f camunda-carbon-reductor-c8/docker-compose.yaml build && \
            docker-compose -f camunda-carbon-reductor-c8/docker-compose.yaml push
          else
            echo "Nothing to build for C8"
          fi
          if [ "$C7" = true ]
          then
            echo "Building C7" && \
            docker-compose -f camunda-carbon-reductor-c7/docker-compose.yaml build && \
            docker-compose -f camunda-carbon-reductor-c7/docker-compose.yaml push
          else
            echo "Nothing to build for C7"
          fi
        env:
          C8: ${{ inputs.c8 }}
          C7: ${{ inputs.c7 }}
